machines:
  Machine_dummy:
    ip: 192.168.1.20
    user: user2
  My_House_Raspberry:
    ip: 192.168.1.18
    user: alvaro_cride
    VRAM: 64GB
    OS: Debian
    ProxyJump:
      ip: 192.168.1.67
      user: m.lorial
  Amazon_machine_2:
    ip: 192.168.1.19
    user: maria_garcia
    VRAM: 24GB
    CPU: 12 cores
    RAM: 128GB

options:
  export_commands_to_machine: True  # Export commands function to remote machine
  connect_timeout: 8  # Maximum connection timeout
  use_ssh_key: True  # Use SSH key instead of password
